name: automation-exercise-github-actions
on: [push]
jobs:
  style_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install Black
        run: python -m pip install --upgrade pip black
      - name: Run Black
        run: black --check .
      - name: Fix formatting with Black
        if: failure()
        run: black .
  #test:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: "test"
  #coverage_report:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: "coverage_report"